### ISSUE TITLE
Create "End Use: <Fuel Type>: Supplemental Heating" workflow output

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-HPXML#1002]
Split out from `End Use: <Fuel Type>: Heating`?
Different from "Secondary Heating"?

Notes from @shorowit:
I think it would be a moderate effort because there are some complications in OS-HPXML (DSE, need to handle HP backup systems that are either integrated or separate systems, etc.), so it would have to be done carefully. And this would presumably create a breaking change for software tools that use OS-HPXML/OS-ERI. But I do see the value in reporting this.

**Comment by whiphi92** [comment]
@ejhw probably important to specify differences between "secondary" heating and "supplemental" heating here. As far as I know "supplemental" is only associated with ASHPs and MSHPs.

**Comment by ejhw** [comment]
@whiphi92 Good point. If it makes things simpler, I'd be fine with grouping HP supplemental together with secondary systems (i.e., space heaters that are a planned addition to ResStock) for end use reporting.

**Comment by ejhw** [comment]
Thanks Scott.  `End Use: <Fuel Type>: Heating Heat Pump Backup` or similar sounds good to me. Maybe do `Heating Heat Pump Integrated Backup` so that it wouldn't imply that it includes backup secondary systems when `Heat Pump: Backup Type` = `separate`.

So there wouldn't be a way to differentiate end use electricity for ductless MSHP heat vs. supplemental electric resistance baseboard if modeled as such, but I suppose you could always model it as ductless MSHP with _integrated_ electric resistance heat to get that break out.

**Comment by ejhw** [comment]
@shorowit The description of `Heat Pump: Backup Type` references "Heating System 2". Isn't that the secondary system? 

> <display_name>Heat Pump: Backup Type</display_name>
> <description>The backup type of the heat pump. If 'integrated', represents e.g. built-in electric strip heat or dual-fuel integrated furnace. If 'separate', represents e.g. electric baseboard or boiler based on the Heating System 2 specified below. Use 'none' if there is no backup heating.</description>

https://github.com/NREL/resstock/blob/6d1932cfa0ac2413b10e5b246af7eb40c98008fc/measures/ResStockArguments/measure.xml#L2141

This description also seems to disagree with what you said about only serving a fraction of load, right?
<display_name>Heating System 2: Fraction Heat Load Served</display_name>
<description>The heat load served fraction of the second heating system. Ignored if this heating system serves as a backup system for a heat pump.</description>

**Comment by shorowit** [comment]
> @shorowit The description of `Heat Pump: Backup Type` references "Heating System 2". Isn't that the secondary system?
> 
> > <display_name>Heat Pump: Backup Type</display_name>
> > The backup type of the heat pump. If 'integrated', represents e.g. built-in electric strip heat or dual-fuel integrated furnace. If 'separate', represents e.g. electric baseboard or boiler based on the Heating System 2 specified below. Use 'none' if there is no backup heating.
> 
> https://github.com/NREL/resstock/blob/6d1932cfa0ac2413b10e5b246af7eb40c98008fc/measures/ResStockArguments/measure.xml#L2141

No, it's just Heating System 2 -- which could be a secondary system or could be a HP separate backup system. If you have ideas on how to clarify this, please suggest them. At one point, Heating System 2 was indeed always a secondary system, but it has since been updated to support being used as a HP separate backup system.

> This description also seems to disagree with what you said about only serving a fraction of load, right?
> 
> > <display_name>Heating System 2: Fraction Heat Load Served</display_name>
> > The heat load served fraction of the second heating system. Ignored if this heating system serves as a backup system for a heat pump.
> > https://github.com/NREL/resstock/blob/6d1932cfa0ac2413b10e5b246af7eb40c98008fc/measures/ResStockArguments/measure.xml#L2339

No, that's consistent with what I said. A heat load fraction applies to a secondary system. A heat load fraction does not apply to a HP backup system, since the operation of a HP backup system is determined dynamically on a timestep basis.

**Comment by ejhw** [comment]
Thanks for explaining, I understand the distinction. I guess it is confusing that what is described as the ["second heating system" in the xml](https://github.com/NREL/resstock/blob/6d1932cfa0ac2413b10e5b246af7eb40c98008fc/measures/ResStockArguments/measure.xml#L2237) is not always a "secondary heating system". But I don't see the word "secondary" used anywhere so maybe it is a moot point. I guess you could use the work "parallel heating system" instead of "secondary" when talking about such a system that serves a fraction of the load in parallel.

If you're saying that `End Use: <Fuel Type>: Heating Heat Pump Backup` will report both integrated and separate backup heat, that's great; I don't see any need to separate.

**Comment by whiphi92** [comment]
I want to make a note here that this fix should also include an additional output that reflects "Delivered Supplemental Heating" (or however we decide to label the output).

**Comment by joseph-robertson** [comment]
https://github.com/NREL/OpenStudio-HPXML/pull/1013 adds:
* `End Use: <Fuel Type>: Heating Heat Pump Backup`

Should it also add:
* Load: Heating Heat Pump Backup: Delivered
* Peak Load: Heating Heat Pump Backup: Delivered

![image](https://user-images.githubusercontent.com/8516790/161597303-1753b254-b9ba-4796-acef-b4edbcfd1d4b.png)
![image](https://user-images.githubusercontent.com/8516790/161597399-92e2a87b-5c8e-423f-963a-d54714477c5c.png)

@shorowit @whiphi92 @ejhw

**Comment by shorowit** [comment]
My vote is for no.

**Comment by ejhw** [comment]
@joseph-robertson  Just to confirm, if left as is, the fields circled above would include delivered heat by all heat sources including heat pump backup?

**Comment by joseph-robertson** [comment]
That's correct.
