### ISSUE TITLE
Investigate duct losses in hourly simulation w/ precooling setpoints

### ISSUE THREAD

**Issue by yzhou601** [NREL/OpenStudio-HPXML#1101]
![image](https://user-images.githubusercontent.com/32500275/170130486-ba8ccfef-1122-411c-a023-64fdd3f6f359.png)
The hourly simulation is showing a different peak hour and different peak hour energy use with other time step simulations.

  | daily total cooling energy (kwh) | peak hour cooling energy (kwh) | peak hour occured | timestep
-- | -- | -- | -- | --
base_time_steps_1_0716_hourly\run\results_timeseries.csv | 80.72 | 2.85 | 2007-07-16T19:00:00 | 1
base_time_steps_5_0716_hourly\run\results_timeseries.csv | 81.89 | 2.81 | 2007-07-16T19:00:00 | 5
base_time_steps_10_0716_hourly\run\results_timeseries.csv | 83.29 | 2.77 | 2007-07-16T19:00:00 | 10
base_time_steps_15_0716_hourly\run\results_timeseries.csv | 84.54 | 2.73 | 2007-07-16T19:00:00 | 15
base_time_steps_30_0716_hourly\run\results_timeseries.csv | 87.64 | 2.52 | 2007-07-16T19:00:00 | 30
base_time_steps_60_0716_hourly\run\results_timeseries.csv | 90.48 | 4.27 | 2007-07-16T17:00:00 | 60

This can be improved by using smaller minimum system timestep. With 10mins minimum system timestep:
![image](https://user-images.githubusercontent.com/32500275/170131346-3015f1a2-cd4d-44a5-aec8-b9eb93ee0dc1.png)

**Comment by shorowit** [comment]
More specifically, we should look at the behavior of the duct model, as it appears to cause the spike in cooling energy during hour 17 in the hourly (60-min zone timestep, 60-min minimum system timestep) simulation.

**Comment by yzhou601** [comment]
> More specifically, we should look at the behavior of the duct model, as it appears to cause the spike in cooling energy during hour 17 in the hourly (60-min zone timestep, 60-min minimum system timestep) simulation.

I actually was a bit lost in that conversation, so the hvac didn't operate during hour 16, and our duct program has one timestep lag (so hour 17 was actually taking hour 16 duct loads, which was 0), how did duct possibly cause the spike at hour 17?

![image](https://user-images.githubusercontent.com/32500275/170142306-2ae38ab1-42c0-4ba2-82a2-9d7bccd61dfc.png)

**Comment by shorowit** [comment]
We have EMS sensors that read the state of the HVAC system (e.g., airflow rate), and then our EMS program calculates the corresponding duct losses and actuates OtherEquipment objects. But changes to the heat gains of the OtherEquipment objects impact the _next_ zone timestep because there is no HVAC iteration loop. (By reducing the minimum system timestep, the heat gains of the OtherEquipment objects can be incorporated into the _current_ zone timestep.)

See [this EMS flow chart](https://bigladdersoftware.com/epx/docs/22-1/ems-application-guide/media/image005.jpg) from the E+ documentation. It shows two system timesteps within a zone timestep, in which case the second "zone load predictor" call will see our actuated duct losses during the same zone timestep. If instead there was only a single system timestep per zone timestep, then the duct losses would be seen the following timestep.

**Comment by shorowit** [comment]
I doubt there is much we can do here. We need something like https://github.com/NREL/OpenStudio-HPXML/issues/636 to address issues like these.
