### ISSUE TITLE
Split battery losses between charging/discharging

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1429]
Can we update our EMS program to split the battery losses between charging and discharging? Currently we lump them all into charging. Did we already try splitting them between charging/discharging and ran into a limitation or problem? I don't see anything in [the PR](https://github.com/NREL/OpenStudio-HPXML/pull/1223) that suggests we tried it, but we might have.

See https://unmethours.com/question/94250/beopt-v3-bess-modeling/ for a BEopt user confused by this.

We won't need to do this if the [E+ efficiency input is connected](https://github.com/NREL/EnergyPlus/issues/9176), but that isn't going to happen in the immediate future.

@jmaguire1 @joseph-robertson

**Comment by jmaguire1** [comment]
@shorowit: So looking at https://github.com/NREL/OpenStudio-HPXML/pull/1223, it doesn't seem like we ever tried splitting between charging and discharging. If I remember right, my thinking at the time was that with the lifetime model and thermal losses could mean that we wouldn't quite get the efficiency exactly right if we split it between charging and discharging, but then we disabled the lifetime model. I don't see any reason we couldn't try splitting this between charging/discharging and so long as we get the overall losses correct make a change here.

**Comment by jmaguire1** [comment]
The last change I made to this was related to efficiency, namely that when you're going from round trip efficiency to charging and discharging efficiency what should that relationship be. I changed this to say the charging_efficiency = discharging_efficiency = round_trip_efficiency ^ 0.5. This is based on the assumption made in [HOMER ](https://www.homerenergy.com/products/pro/docs/3.11/battery_charge_efficiency.html), although I haven't found many other people either using this assumption or justifying it.

The reason this is even an issue is that battery efficiency is a rather complex function of how much you charge/discharge the battery. So in practice, the same Tesla powerwall cycled from the min/max SoC daily will have a different round trip efficiency than if that battery cycled between 40% and 70% SoC each day. Efficiency is also a function of battery temperature, which complicates things even further.

If we're trying to keep this pretty simple (at least until we can leverage SAM directly), it seems our two options from going from round trip efficiency to charging/discharging efficiency are to use the square root of round trip efficiency or split the losses evenly between charging and discharging. Turns out it's not that big an impact either way you do it, at least for reasonable values of round trip efficiency:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jmaguire/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jmaguire/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Round   Trip Efficiency | Charging   Efficiency (square root) | Charing   Efficiency (Even Split)
-- | -- | --
99.00% | 99.50% | 99.50%
98.00% | 99.00% | 98.99%
97.00% | 98.50% | 98.49%
96.00% | 98.00% | 97.98%
95.00% | 97.50% | 97.47%
94.00% | 97.00% | 96.95%
93.00% | 96.50% | 96.44%
92.00% | 96.00% | 95.92%
91.00% | 95.50% | 95.39%
90.00% | 95.00% | 94.87%
89.00% | 94.50% | 94.34%
88.00% | 94.00% | 93.81%
87.00% | 93.50% | 93.27%
86.00% | 93.00% | 92.74%
85.00% | 92.50% | 92.20%
84.00% | 92.00% | 91.65%
83.00% | 91.50% | 91.10%
82.00% | 91.00% | 90.55%
81.00% | 90.50% | 90.00%
80.00% | 90.00% | 89.44%



</body>

</html>

**Comment by jmaguire1** [comment]
I also talked to Michael Blonsky about this, here was his take on how to split round trip efficiency out:

"the square root is better. That's because the energy out = energy in * charge efficiency * discharge efficiency". Which intuitively makes sense to me, and it's not going to be a huge impact regardless.

@shorowit : if you're comfortable with using the square root of round trip efficiency I think this is ready to go. If you're not, lets talk about it.
