### ISSUE TITLE
Stratified Water Heater Specified Source Side Inlet Height and Source Side Outlet Height seem incorrect

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio-HPXML#1848]
**HPXML to OpenStudio" workflow, version : v1.8**
**Filename: "waterheater.rb"**

**Expected Behavior:**
When modeling a WaterHeaterStratified object, would expect the source inlet and source outlet heights to differ. 

**Observed Behavior**:
See code here:
https://github.com/NREL/OpenStudio-HPXML/blob/e770f42307069ba1ed46467ddaee3866d2f70551/HPXMLtoOpenStudio/resources/waterheater.rb#L2013

The current code uses the same value of (0) when calling the methods "setSourceSideInletHeight" and "setSourceSideOutletHeight"

**Suggested fix**
Per the EnergyPlus documentation, consider not setting these values to (0), but rather let them default to the top and bottom heights of the tank, respectively, by not setting them at all.

**Comment by jmaguire1** [comment]
You are correct that we probably do want to set this to have source inlet at bottom of the tank and outlet at the top of the tank by default, rather than source supply/return in the same spot. This would only have an impact if we use a stratified tank model with some sort of indirect WH (like if you had water go to a boiler in a large central system, or if there's a pumped heat pump. So I don't think this is actually going to give us erroneous results, but better to fix this now so we don't run into issues later. If you've actually hit an error trying to set up a system like this that'd be good to note, so we can include in the changelog that we've fixed errors related to those types of systems.

We should set source side inlet height to be something like 0.99 * tank height (or to be consistent with our other calculations being 12 nodes, it could be 11.5/12 * tank height, so 0.958333 * tank height). So long as it end up in node 1 (the top node) the exact value isn't super important.

**Comment by shorowit** [comment]
Thanks @jmaguire1, I can make that change.
