### ISSUE TITLE
Getting started with Docker image

### ISSUE THREAD

**Issue by jefffriesen** [NREL/OpenStudio-HPXML#505]
I'm trying to get this running with the docker image: https://hub.docker.com/r/nrel/openstudio

The instructions here (https://openstudio-hpxml.readthedocs.io/en/latest/getting_started.html) say:

1. Download OpenStudio 3.0.0 and install the Command Line Interface/EnergyPlus components, or use the nrel/openstudio docker image.
2. Download the latest release for these OpenStudio measures.

Are the OpenStudio measures required to be downloaded within the docker container? If they aren't already included in the docker file then that's where I would guess I'm having problems. 

It's not clear to me how to download these and where to put them within the container. The "getting started" points back to the two points listed above.

I've pulled the lated docker container. I can get into a ruby shell within it:
```
docker run -it --rm nrel/openstudio bash
irb
require 'openstudio'
puts OpenStudio.getOpenStudioCLI
```
> /usr/local/openstudio-3.1.0-rc1/bin/openstudio
> nil

`openstudio` is available on the command line:
```
openstudio energyplus_version
> 9.4.0
openstudio openstudio_version
> 3.1.0-rc1+062e7a8260
```

However there is no `run_simulation.rb` or `base.xml` in the container filesystem to run this:
```
openstudio workflow/run_simulation.rb -x workflow/sample_files/base.xml
```

Questions:
1. Do I have the right image? Or do I need a special HPXML OpenStudio image?
2. Do I have to install measures to get `run_simulation.rb`?

Thanks

**Comment by shorowit** [comment]
Hi @jefffriesen,

I think you are close. However,
1. You need to use the specified version of the docker container. So that would be `nrel/openstudio:3.0.0`. (Though if you did use the wrong version, you'll simply get an error message when you call `run_simulation.rb` that you need OpenStudio version 3.0.0.)
2. The `run_simulation.rb` script (and the measures that it calls) is a part of this repository and not the base OpenStudio docker container. So you'll want to download and unzip the [latest release](https://github.com/NREL/OpenStudio-HPXML/releases/tag/v0.11.0-beta) from this repo. Then I think you can execute something like:
`docker run -it --rm -v=/path/to/OpenStudio-HPXML:/var/simdata/openstudio nrel/openstudio /usr/bin/openstudio workflow/run_simulation.rb -x workflow/sample_files/base.xml`

**Comment by shorowit** [comment]
(Alternatively you could grab the OpenStudio-HPXML release from inside the docker container. The example above was for the case where you put the OpenStudio-HPXML release on the host machine.)

**Comment by jefffriesen** [comment]
@shorowit This works. I downloaded the data from within the docker container so that it's all self "contained".  For our use I may create a docker container that includes both OpenStudio and OpenStudio-HPXML along with some additional processing. 

I was a little confused on the getting started. Would you want me to do a documentation PR to try to clarify it a little? If not no problem.

Thanks

**Comment by shorowit** [comment]
Glad you got it working! Yes, we'd be happy to receive any suggested improvements to the documentation.
