### ISSUE TITLE
Add optional building_id argument to HPXMLtoOpenStudio measure for files with multiple buildings

### ISSUE THREAD

**Issue by pegdeploy** [NREL/OpenStudio-HPXML#574]
The standard home performance use case for HPXML has two buildings (pre and post retrofit).  Adding a building_id argument would allow a large quantity of existing HPXML files to be used in this integration.

**Comment by GamalielL** [comment]
Oops.  Accidentally submitted this from the wrong account.

**Comment by shorowit** [comment]
I agree that OS-HPXML should be able to support multiple buildings. I think my preference would be to not add an additional measure argument, but rather specify the building to be simulated within the HPXML itself, as that would allow us to check for appropriate inputs as part of the EPvalidator.xml Schematron validation.

If there are multiple `Building` elements, we could introduce a required `SimulationControl/Building` element like:

```xml
<HPXML>
  <SoftwareInfo>
    <extension>
      <SimulationControl>
        <Building idref='Building1'/>
        ...
      </SimulationControl>
    </extension>
  </SoftwareInfo>
  <Building>
    <BuildingID id='Building1'/>
    ...
  </Building>
  <Building>
    <BuildingID id='Building2'/>
    ...
  </Building>
</HPXML>
```

If there is only one `Building` element, nothing would have to be specified.

**Comment by GamalielL** [comment]
The problem with that is that it doesn't allow us to easily run files that were created for some other purpose.  For instance we could have a file generated as part of a home performance program using another software's energy results.  If we wanted to come back after the fact and compare results from OpenStudio, then we have to make two separate manual edits of that file, in order to run the pre and post retrofit buildings.  If we use a measure argument, then the whole process can be automated and batches of files can be analyzed.

**Comment by shorowit** [comment]
Good point, @GamalielL. There are some small things I don't like about using an argument to specify which building to simulate, but I suppose we just have to live with them.
