### ISSUE TITLE
Water heater GEB

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#635]
Add new GEB features such as:

- Allowing tanks to use either a mixed or stratified tank model (additional user argument)
- Allowing setpoint to follow an hourly (8760) schedule rather than only fixed values.
- Allowing HPWH operating mode to be scheduled (either "HP Only" or "standard"). This allows the elements to be disabled during peak periods.
- Adding unmet shower (an unmet load metric for WHs) calculations to quantify any unmet WH loads.

**Comment by shorowit** [comment]
Related: https://github.com/NREL/OpenStudio-HPXML/issues/844

**Comment by shorowit** [comment]
Please allow schedule CSV files to be used w/ more than 8760 values (e.g., if running at shorter timesteps than hourly).

**Comment by joseph-robertson** [comment]
Do we want to require that water heater setpoint and operating mode schedules be (A) included in the CSV file referenced by `SchedulesFilePath`, or (B) included in separate CSV files?

(A) Same file would mean that all building features use detailed schedules. We would also need to modify the `validate_schedules` method to handle schedule values greater than one. How would the `BuildResidentialScheduleFile` measure deal with this? Would it only write "smooth" schedules for water heater setpoint and operating mode?

(B) Separate files would mean there'd be more than one field in the HPXML file with CSV file paths.

I suppose these same questions apply to #844.

**Comment by joseph-robertson** [comment]
Have arguments in `BuildResidentialScheduleFile` for "Water Heater Setpoint Schedule Path" and "Water Heater Operating Mode Schedule Path". The measure would write the path(s) alongside existing `SchedulesFilePath` element. It would point to Jeff's schedule files.

Could add the other two arguments, "tank type" and "constant operating mode", to `BuildResidentialHPXML`. We could default tank type to stratified, but would need testing for speed.

Need to think about error handling around, e.g., having both constant water heater setpoint in hpxml and schedule file path with 8760 setpoint schedule.

For #844, we would have separate heating and cooling setpoint schedule arguments.

**Comment by joseph-robertson** [comment]
@jmaguire1 to describe his mixed vs stratified tank findings at the next residential modeling planning meeting.

**Comment by jmaguire1** [comment]
Since this pull request allows you to specify whether you want to use the mixed or stratified tank model, I did some runs of both models so we could compare the runtime and energy impacts of the WH model fidelity. I ran simulations of an electric resistance tank in either a low use (1 occupant) or high use (5 occupant) single family detached home at either a 10 minute or 60 minute timestep. In terms of results, I was primarily looking at overall run time, annual energy consumption, and unmet shower energy (a relatively new discomfort metric I've been pushing that's included in this PR). Here's a summary of the results:

![image](https://user-images.githubusercontent.com/8376057/150829563-ee6be86b-6454-48b1-9a1b-d44927a3c390.png)

I want to make a couple points here:

1. In terms of run time, the stratified tank does take longer, which isn't terribly surprising. The run time impacts are larger if you have more hot water usage since the WH needs to make a lot more control decisions under higher hot water usage, so the adaptive timestep code Noel added to the stratified tank model is subdividing the timesteps much more frequently for high usage homes. In low usage homes the runtime impact might only be 10-20%, but for high usage homes it's a pretty substantial increase.
2. Energy consumption predictions are pretty consistent between the two models, it's ~1% difference so not particularly concerned there.
3. Comfort predictions, on the other hand, are quite a bit different between the models. At a 10 minute timestep, the discomfort even in a low usage home is surprisingly high. Looking at the draw profile, there are times where the flow rate is very high and as a result the tank does get pretty substantially depleted. With the stratified tank, you have a top element that's trying to heat a smaller volume of hot water so you see faster recovery after a large draw when you're modeling with a stratified tank instead of a mixed tank. This to me seems like the biggest upside of the stratified tank model, that we're going to be able to more realistically capture discomfort for an electric resistance water heater. 

I think we probably need to discuss some of these results, since it's not entirely clear cut to me what we ought to do here. @shorowit
