### ISSUE TITLE
Time column in results_timeseries.csv

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-HPXML#928]
See https://github.com/NREL/resstock/pull/528 for reference.

Short-term fix:
- [x] Correct Time column to represent local standard time no matter the timezone that the simulation is run: https://github.com/NREL/OpenStudio-HPXML/pull/929

We are seeing that `Time` timestamps can differ depending on where the simulation is run. We should switch to UTC.
Include "UTC" in results_timeseries.csv header.

Another idea, to support one column of Time, is to include arguments in ReportSimulationOutput that determine what Time represents:
- local standard time, local clock time (w/DST), or UTC
- if UTC, provide dropdown with timezone (or stored in hpxml file or determined from county)

Questions:
- Do we want to include a "TimeDST" column? Sounds like maybe? This could be done in postprocessing?
- Use location of the building if available?
- Leave this alone in OS-HPXML and modify the output using postprocessing with `smartquery`?
- Perhaps two columns, standard and clock, would be best

@whiphi92 @aspeake @ejhw @shorowit

**Comment by ejhw** [comment]
In addition to including UTC in the header, I would even be in favor of including "UTC" in the time format itself, which seems to be standard:
![image](https://user-images.githubusercontent.com/1276021/144514015-3776eef6-ee40-41b7-b37e-aaa4318fb689.png)

**Comment by whiphi92** [comment]
It is important to have a time column of a static time reference, whether it be local standard time, local daylight time, or UTC time (these are the three timestamps used on ResStock Athena timeseries). 

If we use local time without a time designation (e.g., using '2015-05-05 05:00:00' rather than '2015-05-05 05:00:00 MDT') and a user aggregates data on the timestamp, the last hour of daylight savings time (1am before fall back) and the first hour of standard time (1am when you fall back) will be aggregated to the same hour.

**Comment by nmerket** [comment]
I'd like to humbly request that we use [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format for all dates. 

![image](https://user-images.githubusercontent.com/5325034/145860992-9bc98482-7d29-43f4-88eb-3375f6bad175.png)

It looks like ruby has a [iso8601 method](https://ruby-doc.org/stdlib-2.6.3/libdoc/date/rdoc/DateTime.html#method-i-iso8601) for converting timestamps to strings.
