### ISSUE TITLE
Duct program behaves suspiciously when duct leakage percentage is big

### ISSUE THREAD

**Issue by yzhou601** [NREL/OpenStudio-HPXML#982]
There's a 30% duct leakage test file where duct program seems to be suspiciously adding heat to the zone for some time steps. It is running one cooling day (07/16), and those timesteps being messed up show heating energy and significant temperature rise.

![image](https://user-images.githubusercontent.com/32500275/154351919-8ee456d9-0cff-43e2-96d4-01daa7366e90.png)
(Cooling setpoint is 78F)

Test [hpxml file](https://drive.google.com/file/d/1Ilu3dLmFHoiS7FXj-mn3Eps3fxKbgStG/view?usp=sharing)

**Comment by shorowit** [comment]
Oops, just saw this issue.

@yzhou601 If you run a week-long simulation then ends on 7/16 (instead of just running the single 7/16 day) and then look at the results for the 7/16 day, do the results look better?

I recall that our duct model has a small issue where it behaves poorly for a bit of time (a few days?). I don't remember the exact details, but I think it's related to EnergyPlus initializing all thermal zones to 23 deg-C. So it takes some time at the beginning of the simulation for zone temperatures to approach realistic temperatures for the beginning of the year (or, in your case, the middle of summer). In a typical annual simulation, it's a minor effect, but if you're running a simulation with a single day (which we don't often do), then it could be a problem.

**Comment by shorowit** [comment]
I doubt there is much we can do here. We need something like https://github.com/NREL/OpenStudio-HPXML/issues/636 to address issues like these.
