### ISSUE TITLE
Requesting user-defined output variables

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-HPXML#997]
The current `ReportSimulationOutput` measure provides standard sets of commonly requested outputs. What if we want to request outputs outside of these standard sets?

Revive `TimeseriesCSVExport` or at least the portion of it that enables requesting output variables? (We could use existing BCL measures like `AddOutputVariable` and its companion reporting measure (?) to make these requests, but how would we integrate the results with `results_timeseries.csv`?)

**Comment by shorowit** [comment]
I am in favor of new optional arguments in the `ReportSimulationOutput` measure that allow user-defined outputs to be included in the timeseries csv.

**Comment by whiphi92** [comment]
Some applications (e.g., testing EC windows) enabled by our new HPXML workflow will require special "non-default" output variables from EnergyPlus. Specifically, enabling "DisplayAdvancedReportVariables" via the "Add Output Diagnostics" measure so that users can see the timeseries output of "SurfaceConstructionIndex".

Info about Add Output Diagnostics: https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-3.3.0-doc/model/html/classopenstudio_1_1model_1_1_output_diagnostics.html

Info about SurfaceConstructionIndex: https://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-energy-management-system-ems.html#energymanagementsystemconstructionindexvariable

Info about Output Variables (DisplayAdvancedReportVariables at bottom of page): https://bigladdersoftware.com/epx/docs/9-1/output-details-and-examples/eplusout-rdd.html

**Comment by joseph-robertson** [comment]
So sounds like we have a `add_component_loads` lever for enabling advanced output variables. Therefore, I don't think we'd need to default to always enabling it. ResStock never used `OutputDiagnostics` AFAIK.

**Comment by joseph-robertson** [comment]
Optionally we could support an argument where users can pass in desired units. If conversion is not given, or does not work (e.g., "deg-F" vs "F"), then just use the sql units.
